### ISSUE TITLE
Create new Debian 8 boxes

### ISSUE THREAD

**Issue by njam** [cargomedia/vagrant-boxes#85]
I think it would be good to speed up the CI deployment.
Please check if there's a new release from Debian.

@kris-lab could you do it?

**Comment by kris-lab** [comment]
Latest boxes have beed made by end on November. There is no ISO release since then. What else did you have in mind @njam? Just update all packages etc?

**Comment by njam** [comment]
Yes, let's create a box with new puppet modules and apt packages then. Hopefully it will reduce build times a bit again.

**Comment by kris-lab** [comment]
New box size - all smaller
```
834M  4 Jan 11:29 debian-8-amd64/artifacts/virtualbox/debian-8-amd64-cm.box
437M  4 Jan 11:03 debian-8-amd64/artifacts/virtualbox/debian-8-amd64-default.box
343M  4 Jan 10:48 debian-8-amd64/artifacts/virtualbox/debian-8-amd64-plain.box
```

**Comment by njam** [comment]
👍 remember to commit Puppetfile.lock

**Comment by kris-lab** [comment]
closing in favor of https://github.com/cargomedia/vagrant-boxes/pull/86
